name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the code
      - name: checkout code
        uses: actions/checkout@v4

      # setup-go
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      # run production build
      - name: build production
        run: ./scripts/buildprod.sh

      # gcp integration
      - name: authenticate to google cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: configure docker for artifact registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      
      - name: build and push docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/notely-487500/notely-ar-repo/notely:latest .
